services:
  web:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - '.:/usr/src/kanrikun'
    env_file:
      - .env/development/web
      - .env/development/database
    tty: true
    stdin_open: true

  database:
    image: mysql:8.2
    ports:
      - "3306:3306"
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
