services:
  web:
    build: .
    ports:
      - '3001:3000'
    volumes:
      - '.:/usr/src/vinylize'
    env_file:
      - .env/development/web
      - .env/development/database
    tty: true
    stdin_open: true

  database:
    image: postgres:16.4
    ports:
      - "5432:5432"
    env_file:
      - .env/development/database
    volumes:
      - vinylize_db_data:/var/lib/postgresql/data

volumes:
  vinylize_db_data:
