name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: bundle install

      - name: Setup Database
        run: |
          cp config/database.ci.yml config/database.yml
          bundle exec rails db:create
          bundle exec rails db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: 'mysql'
          DATABASE_PASSWORD: 'mysql'

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Run RSpec
        run: bin/rspec
        env:
          DATABASE_USERNAME: 'mysql'
          DATABASE_PASSWORD: 'mysql'
